name: Main Branch Integration Workflow

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Integrate
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust 
        uses: actions-rs/toolchain@v1 
        with: 
          toolchain: stable 
          profile: minimal 
          override: true 
      - name: Build native
        run: cargo build --verbose 
      - name: Run tests 
        run: cargo test --verbose -- --nocapture
      - name: Build web
        run: cargo xtask build-web-dist
      - name: Copy folder to where nginx expects it to be
        run: rsync -vr --delete ${{secrets.COPY_FROM_FOLDER}} ${{secrets.COPY_TO_FOLDER}}
